In [3]:
import sys
sys.path.append('../src/')
import dust2dusty
import numpy as np

In [4]:
import argparse
args = argparse.Namespace(
    CONFIG_FILE='../config/config_popovic2023.yml',
    OUTPUT_DIR='./TEST_OUTPUT',
    TEST_RUN=False,
    DEBUG_RUN=False,
    DEBUG_FULL=False,
    NOWEIGHT=False,
    VERBOSE=False,
    FORCE_OVERRIDE=True,
    SAMPLER="emcee"
)


In [5]:
import logging
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [%(levelname)s] %(message)s",
    stream=sys.stdout,   # notebooks buffer stderr; stdout shows immediately
    force=True,          # re-configures if logging was already set up
)
log = logging.getLogger(__name__)

In [6]:
import importlib

importlib.reload(dust2dusty.utils)

importlib.reload(dust2dusty.cli)
importlib.reload(dust2dusty)


<module 'dust2dusty' from '/hpc/group/cosmology/blc56/Soft/dust2dusty/debug_notebooks/../src/dust2dusty/__init__.py'>

In [7]:
import yaml

In [8]:
with open(args.CONFIG_FILE, "r") as f:
    data = yaml.safe_load(f)

In [9]:
cfg = dust2dusty.cli._load_config(args, log)

2026-03-16 16:31:17,587 [INFO] Loaded configuration from: ../config/config_popovic2023.yml
2026-03-16 16:31:17,588 [WARNING] Removing existing output directory: /hpc/group/cosmology/blc56/Soft/dust2dusty/debug_notebooks/TEST_OUTPUT
2026-03-16 16:31:17,617 [DEBUG] Create main directory /hpc/group/cosmology/blc56/Soft/dust2dusty/debug_notebooks/TEST_OUTPUT
2026-03-16 16:31:17,627 [DEBUG] Create sub directory /hpc/group/cosmology/blc56/Soft/dust2dusty/debug_notebooks/TEST_OUTPUT/chains
2026-03-16 16:31:17,628 [DEBUG] Create sub directory /hpc/group/cosmology/blc56/Soft/dust2dusty/debug_notebooks/TEST_OUTPUT/logs
2026-03-16 16:31:17,630 [DEBUG] Create sub directory /hpc/group/cosmology/blc56/Soft/dust2dusty/debug_notebooks/TEST_OUTPUT/realdata_salt2mu_files
2026-03-16 16:31:17,631 [DEBUG] Create sub directory /hpc/group/cosmology/blc56/Soft/dust2dusty/debug_notebooks/TEST_OUTPUT/worker_salt2mu_files
2026-03-16 16:31:17,632 [INFO] Configuration finalized successfully:
2026-03-16 16:31:17,63

In [10]:
args

Namespace(CONFIG_FILE='../config/config_popovic2023.yml', OUTPUT_DIR='./TEST_OUTPUT', TEST_RUN=False, DEBUG_RUN=False, DEBUG_FULL=False, NOWEIGHT=False, VERBOSE=False, FORCE_OVERRIDE=True, SAMPLER='emcee', USE_MPI=False)

In [31]:
cfg.fitted_params

{'c': {'dist': 'Gaussian'},
 'RV': {'dist': 'Gaussian', 'splits': {'HOST_LOGMASS': 10}},
 'EBV': {'dist': 'Exponential',
  'splits': {'SIM_ZCMB': 0.1, 'HOST_LOGMASS': 10}},
 'beta': {'dist': 'Gaussian'}}

In [15]:
sampled_par_names, p0_init, p0_std, p0_bounds, log_sampling = dust2dusty.utils.get_sampled_par_names_and_init(cfg) 



In [20]:
RV_GRID = dust2dusty.SALT2mu.DEFAULT_PARAMETER_RANGES['RV']

HOST_LOGMASS_GRID = np.arange(5,15,1)

RV, HLM = np.meshgrid(RV_GRID,HOST_LOGMASS_GRID)

In [24]:
P = np.zeros_like(RV)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [26]:
P[HLM < 10] = RV[HLM < 10]

In [30]:
 {k.replace(pattern, ""): v for k, v in d.items() if pattern in k}

array([ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7

In [29]:
P.flatten()

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ,
       1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3,
       2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6,
       3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9,
       5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2,
       6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5,
       7.6, 7.7, 7.8, 7.9, 0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8,
       0.9, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.

In [40]:
%%time
theta_dic = dict(zip(sampled_par_names, p0_init))

CPU times: user 10 μs, sys: 0 ns, total: 10 μs
Wall time: 12.6 μs


In [56]:
param_name = 'RV'
param_dist_vals_dic = {k: v for k, v in theta_dic.items() if param_name in k}
split_pars = list(cfg.fitted_params['RV']["splits"].keys())


In [59]:
param_vals = {}
for l in ["low", "high"]:
    param_vals[l] = {
        k.replace(f"_{split_pars[0]}_{l}", ""): v
        for k, v in param_dist_vals_dic.items()
        if f"_{split_pars[0]}_{l}" in k
    }


In [60]:
param_vals

{'low': {'RV_mu': np.float64(3.026), 'RV_std': np.float64(0.3927175352856618)},
 'high': {'RV_mu': np.float64(2.138),
  'RV_std': np.float64(0.058268908123975824)}}

In [53]:
%%timeit
pattern = '_HOST_LOGMASS_high'
{k.replace(pattern, ""): v for k, v in param_dist_vals_dic.items() if pattern in k}

377 ns ± 0.821 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [37]:
theta_dic = dict(zip(["par_names"], theta))


NameError: name 'theta' is not defined

In [33]:
theta_dic

NameError: name 'theta_dic' is not defined

In [ ]:
param_dist_values = p0_init[np.char.startswith(sampled_par_names, 'RV')]

temp = []
n_shape_params = len(cfg.DISTRIBUTION_PARAMETERS[cfg.fitted_params['RV']['dist']])
for i in range(len(cfg.fitted_params['RV']['splits'].keys()) * 2):
    temp.append(param_dist_values[i * n_shape_params : (i + 1) * n_shape_params])
temp

In [ ]:
getattr(np, 'arange')

In [ ]:
np.arange(*[5, 15,1])

In [ ]:
from itertools import combinations
def get_sampled_par_names_and_init(config) -> list[str]:
    sampled_par_names = []
    for p, pdic in config.fitted_params.items():
        if "splits" not in pdic:
            sampled_par_names.extend(
                [f"{p}_{dist_p}" for dist_p in config.DISTRIBUTION_PARAMETERS[pdic["dist"]]]
            )
        else:
            splits = pdic["splits"].keys()
            split_string = f"{p}_{{}}_" + "_".join([f"{split_p}_{{}}" for split_p in splits])
            split_states = []
            for r in range(len(splits) + 1):
                for low_vars in combinations(splits, r):
                    split_states.append(["low" if v in low_vars else "high" for v in splits])

            sampled_par_names.extend(
                [
                    split_string.format(dist_p, *split_st)
                    for split_st in split_states
                    for dist_p in config.DISTRIBUTION_PARAMETERS[pdic["dist"]]
                ]
            )
    p0_mu = np.array([config.parameter_inits[p]["p0"] for p in sampled_par_names])
    p0_std = np.array([config.parameter_inits[p]["p0_std"] for p in sampled_par_names])
    log_sampling = np.array(
        [True if "tau" in p or "std" in p else False for p in sampled_par_names], dtype=bool
    )

    # log sampling of variance
    p0_mu[log_sampling] = np.log(p0_mu[log_sampling])
    p0_std[log_sampling] = np.log(p0_std[log_sampling])

    par_bounds = np.array(
        [
            config.parameter_inits[p]["bounds"]
            if not log_sampling[i]
            else [-np.inf, np.log(config.parameter_inits[p]["bounds"][-1])]
            for i, p in enumerate(sampled_par_names)
        ]
    )

    return sampled_par_names, p0_mu, p0_std, par_bounds, log_sampling


In [ ]:
pconv(cfg.fitted_params, cfg.param_dists, cfg.param_splits, cfg.DISTRIBUTION_PARAMETERS)

In [ ]:
splits_on = cfg.param_splits['EBV'].keys()


In [ ]:
p = "RV"
cfg.DISTRIBUTION_PARAMETERS[cfg.param_dists[p]]

In [ ]:
def pconv(
    inp_params: list[str],
    paramshapesdict: dict[str, str],
    splitdict: dict[str, dict[str, float]],
    distribution_parameters: dict[str, list[str]],
) -> list[str]:
    """
    Convert input parameters to expanded parameter list.

    Takes high-level parameter names and expands them into a full list of
    distribution parameters, accounting for:
    1. Distribution shape (Gaussian needs mu+std, Exponential needs tau, etc.)
    2. Parameter splits (e.g., different values for low/high mass)

    Example:
        >>> pconv(['RV'], {'RV': 'Gaussian'}, {'RV': {'HOST_LOGMASS': 10}},
        ...       {'Gaussian': ['mu', 'std']})
        ['RV_HOST_LOGMASS_low_mu', 'RV_HOST_LOGMASS_low_std',
         'RV_HOST_LOGMASS_high_mu', 'RV_HOST_LOGMASS_high_std']

    Args:
        inp_params: List of high-level parameter names (e.g., ['c', 'RV', 'EBV']).
        paramshapesdict: Maps parameter to distribution shape
            (e.g., {'c': 'Gaussian'}).
        splitdict: Nested dict defining parameter splits.
            Format: {param: {split_var: split_value}}.
            Example: {'RV': {'HOST_LOGMASS': 10, 'SIM_ZCMB': 0.1}}.
        distribution_parameters: Dict mapping distribution names to their
            parameter names (e.g., {'Gaussian': ['mu', 'std']}).

    Returns:
        Expanded parameter names (length = ndim for MCMC).
        Format: 'PARAM_SPLITVAR1_lowhigh_SPLITVAR2_lowhigh_..._DISTPARAM'.
    """
    inpfull: list[list[str]] = []
    for i in inp_params:
        initial_dimension = list(distribution_parameters[paramshapesdict[i]])
        if i in splitdict.keys():
            things_to_split_on = splitdict[i]
            nsplits = len(things_to_split_on)
            params_to_split_on = things_to_split_on.keys()
            # Create format string like "{}_{}_{}_{}" for nsplits*2 parameters
            format_string = "_".join(["{}"] * nsplits * 2)
            lowhigh_array = np.tile(["low", "high"], [nsplits, 1])
            splitlist = []
            for lowhigh_combo in itertools.product(*lowhigh_array):
                to_format = [val for pair in zip(params_to_split_on, lowhigh_combo) for val in pair]
                final = format_string.format(*to_format)
                splitlist.append(final)
            initial_dimension = [
                tmp[1] + "_" + tmp[0] for tmp in itertools.product(splitlist, initial_dimension)
            ]
        final_dimension = [i + "_" + s for s in initial_dimension]
        inpfull.append(final_dimension)
    return [item for sublist in inpfull for item in sublist]
